name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nestmongo:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploying:
      needs: build
      runs-on: windows-latest
      steps:
        - name: Connecting to windows and Deploying Image.
          uses: appleboy/ssh-action@master
          with:
            host: 116.75.110.243
            username: manikanta\manikanta
            password: 9430 
            port: 22
            script: |
              docker login -u manitrak -p Mani@9430
              docker stop user
              docker rm user
              docker pull manitrak/nestmongo:latest
              docker run --network="host" --name nest -d  manitrak/nestmongo:latest
