name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
        
  Deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS Creditentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          #host: ip-172-31-36-219.ap-south-1.compute.internal
          aws-access-key-id: AKIA3MX5DVVFM2PNJW5Z
          aws-secret-access-key: 9BwedT429mNzwe/BHnu4ldm0kC8dykdOrD4riUWi
          aws-region: ${{ env.AWS_REGION }}
          #port: ${{ secrets.PORT }}
          script: |
            sample string
  
        

        
