name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  deploying:
      #needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Connecting to windows and Deploying Image.
          uses: appleboy/ssh-action@master
          with:
            host: 192.168.71.128
            username: mani
            password: 9430 
            port: 22
            script: |
              mkdir manitest
