name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  deploying:
      #needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Connecting to windows and Deploying Image.
          uses: appleboy/ssh-action@master
          with:
            host: 116.75.110.243
            username: manikanta\manikanta
            password: 9430 
            port: 22
            script: |
              docker login -u manitrak -p Mani@9430
              docker stop user
              docker rm user
              docker pull manitrak/nestmongo:latest
              docker run --network="host" --name nest -d  manitrak/nestmongo:latest
