name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nestmongo:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
  Deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Pull Docker Image
        #uses: manitrak/nest-mongo-notesapp@main
        with:
          host: ip-172-31-36-219.ap-south-1.compute.internal
          username: maniam
          password: 9BwedT429mNzwe/BHnu4ldm0kC8dykdOrD4riUWi
          #port: ${{ secrets.PORT }}
          script: |
            sample string
  
        

        
